# Generated by Django 2.0 on 2018-06-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastes',
            name='id',
        ),
        migrations.AlterField(
            model_name='pastes',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
